version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # Install yarn
      - apt update
      - apt install --no-install-recommends yarn
      #- curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash
      #- sudo apt-get install -y nodejs

      # Install firebase tools
      - yarn global add firebase-tools@10.9.2

  pre_build:
    commands:
      # Install all root dependencies
      - make install

  post_build:
    commands:
      # Deploy the firebase application using project & CI Token
      - make firebase-deploy-simple project=$FIREBASE_PROJECT token=$(make decrypt-deprecated decrypt_value=$FIREBASE_TOKEN)
